package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Gymbadge;

public interface GymbadgeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GYMBADGE
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GYMBADGE
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    int insert(Gymbadge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GYMBADGE
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    Gymbadge selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GYMBADGE
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    List<Gymbadge> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GYMBADGE
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    int updateByPrimaryKey(Gymbadge record);
}