package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Pokemon;
import org.mybatis.cdi.Mapper;

@SuppressWarnings("CdiManagedBeanInconsistencyInspection")
@Mapper
public interface PokemonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.POKEMON
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.POKEMON
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    int insert(Pokemon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.POKEMON
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    Pokemon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.POKEMON
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    List<Pokemon> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.POKEMON
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    int updateByPrimaryKey(Pokemon record);
}