package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Trainer;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface TrainerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRAINER
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRAINER
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    int insert(Trainer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRAINER
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    Trainer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRAINER
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    List<Trainer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRAINER
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    int updateByPrimaryKey(Trainer record);
}