package lt.vu.mybatis.model;

public class Gymbadge {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GYMBADGE.ID
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GYMBADGE.GYMNAME
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    private String gymname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GYMBADGE.ID
     *
     * @return the value of PUBLIC.GYMBADGE.ID
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GYMBADGE.ID
     *
     * @param id the value for PUBLIC.GYMBADGE.ID
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GYMBADGE.GYMNAME
     *
     * @return the value of PUBLIC.GYMBADGE.GYMNAME
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    public String getGymname() {
        return gymname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GYMBADGE.GYMNAME
     *
     * @param gymname the value for PUBLIC.GYMBADGE.GYMNAME
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    public void setGymname(String gymname) {
        this.gymname = gymname;
    }
}