package lt.vu.mybatis.model;

public class Pokemon {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.POKEMON.ID
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.POKEMON.COMBATPOWER
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    private Integer combatpower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.POKEMON.LEVEL
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.POKEMON.NAME
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.POKEMON.NUMBER
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.POKEMON.TRAINER_ID
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    private Integer trainerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.POKEMON.ID
     *
     * @return the value of PUBLIC.POKEMON.ID
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.POKEMON.ID
     *
     * @param id the value for PUBLIC.POKEMON.ID
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.POKEMON.COMBATPOWER
     *
     * @return the value of PUBLIC.POKEMON.COMBATPOWER
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    public Integer getCombatpower() {
        return combatpower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.POKEMON.COMBATPOWER
     *
     * @param combatpower the value for PUBLIC.POKEMON.COMBATPOWER
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    public void setCombatpower(Integer combatpower) {
        this.combatpower = combatpower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.POKEMON.LEVEL
     *
     * @return the value of PUBLIC.POKEMON.LEVEL
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.POKEMON.LEVEL
     *
     * @param level the value for PUBLIC.POKEMON.LEVEL
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.POKEMON.NAME
     *
     * @return the value of PUBLIC.POKEMON.NAME
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.POKEMON.NAME
     *
     * @param name the value for PUBLIC.POKEMON.NAME
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.POKEMON.NUMBER
     *
     * @return the value of PUBLIC.POKEMON.NUMBER
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.POKEMON.NUMBER
     *
     * @param number the value for PUBLIC.POKEMON.NUMBER
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.POKEMON.TRAINER_ID
     *
     * @return the value of PUBLIC.POKEMON.TRAINER_ID
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    public Integer getTrainerId() {
        return trainerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.POKEMON.TRAINER_ID
     *
     * @param trainerId the value for PUBLIC.POKEMON.TRAINER_ID
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    public void setTrainerId(Integer trainerId) {
        this.trainerId = trainerId;
    }
}