package lt.vu.mybatis.model;

public class TrainerBadge {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRAINER_BADGE.TRAINER_ID
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    private Integer trainerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRAINER_BADGE.GYMBADGES_ID
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    private Integer gymbadgesId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRAINER_BADGE.TRAINER_ID
     *
     * @return the value of PUBLIC.TRAINER_BADGE.TRAINER_ID
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    public Integer getTrainerId() {
        return trainerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRAINER_BADGE.TRAINER_ID
     *
     * @param trainerId the value for PUBLIC.TRAINER_BADGE.TRAINER_ID
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    public void setTrainerId(Integer trainerId) {
        this.trainerId = trainerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRAINER_BADGE.GYMBADGES_ID
     *
     * @return the value of PUBLIC.TRAINER_BADGE.GYMBADGES_ID
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    public Integer getGymbadgesId() {
        return gymbadgesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRAINER_BADGE.GYMBADGES_ID
     *
     * @param gymbadgesId the value for PUBLIC.TRAINER_BADGE.GYMBADGES_ID
     *
     * @mbg.generated Mon Apr 27 20:55:42 EEST 2020
     */
    public void setGymbadgesId(Integer gymbadgesId) {
        this.gymbadgesId = gymbadgesId;
    }
}